title: # TITLE REQUIRED #
author: # AUTHOR REQUIRED #
logo: _static/qe-logo-large.png
description: # DESCRIPTION REQUIRED #

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 2400

bibtex_bibfiles:
   - _static/quant-econ.bib

# latex:
#    latex_documents:
#       targetname: {{ NAME OF PDF DOCUMENT }}

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinxcontrib.youtube, sphinx.ext.todo, sphinx_exercise, sphinx_proof, sphinx_togglebutton, sphinx.ext.intersphinx, sphinx_reredirects]
  config:
    linkcheck_ignore: []  # false-positive links
    bibtex_reference_style: author_year
    nb_mime_priority_overrides: [
       # HTML
       ['html', 'application/vnd.jupyter.widget-view+json', 10],
       ['html', 'application/javascript', 20],
       ['html', 'text/html', 30],
       ['html', 'text/latex', 40],
       ['html', 'image/svg+xml', 50],
       ['html', 'image/png', 60],
       ['html', 'image/jpeg', 70],
       ['html', 'text/markdown', 80],
       ['html', 'text/plain', 90],
       # Jupyter Notebooks
       ['jupyter', 'application/vnd.jupyter.widget-view+json', 10],
       ['jupyter', 'application/javascript', 20],
       ['jupyter', 'text/html', 30],
       ['jupyter', 'text/latex', 40],
       ['jupyter', 'image/svg+xml', 50],
       ['jupyter', 'image/png', 60],
       ['jupyter', 'image/jpeg', 70],
       ['jupyter', 'text/markdown', 80],
       ['jupyter', 'text/plain', 90],
       # LaTeX
       ['latex', 'text/latex', 10],
       ['latex', 'application/pdf', 20],
       ['latex', 'image/png', 30],
       ['latex', 'image/jpeg', 40],
       ['latex', 'text/markdown', 50],
       ['latex', 'text/plain', 60],
       # Link Checker
       ['linkcheck', 'text/plain', 10],
     ]
    html_favicon: _static/lectures-favicon.ico
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      authors:
        - name: # AUTHOR REQUIRED #
          url: # URL FOR AUTHOR WEBSITE #
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      repository_url: # REPOSITORY URL REQUIRED #
      # nb_repository_url: 
      twitter: quantecon
      twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: 
      keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
      # analytics:
      #   google_analytics_id: 
      launch_buttons:
        colab_url                 : https://colab.research.google.com
    intersphinx_mapping: 
      intro: 
        - "https://intro.quantecon.org/"
        - null
    mathjax3_config:
      tex:
        macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # Local Redirects
    rediraffe_redirects:
      index_toc.md: intro.md
    # tojupyter_static_file_path: ["source/_static", "_static"]
    # tojupyter_target_html: true
    # tojupyter_urlpath: "https://python.quantecon.org/"
    # tojupyter_image_urlpath: "https://python.quantecon.org/_static/"
    # tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    # tojupyter_kernels:
    #   python3:
    #     kernelspec:
    #       display_name: "Python"
    #       language: python3
    #       name: python3
    #     file_extension: ".py"
    # tojupyter_images_markdown: true
