name: Build & Publish to GH Pages
on:
  push:
    tags:
      - 'publish*'
jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: quantecon-gpu
    container:
      image: ghcr.io/quantecon/lecture-python-container:cuda-12.6.0-anaconda-2024-10-py312-b
      options: --gpus all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Git (required to commit notebooks)
        shell: bash -l {0}
        run: apt-get install -y git
      - name: Check nvidia drivers
        shell: bash -l {0}
        run: |
          nvidia-smi
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      # Final HTML
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./
      - name: Deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
          cname: python.quantecon.org

